apiVersion: v1
kind: Service
metadata:
  namespace: ngmanager
  name: ngmanager-gateway
  labels:
    app: ngmanager-gateway
spec:
  ports:
    - port: 9000
      protocol: TCP
      name: http
    - port: 9001
      protocol: TCP
      name: grpc
  selector:
    app: ngmanager-gateway