apiVersion: v1
kind: Service
metadata:
  namespace: ngmanager
  name: ngmanager-web
  labels:
    app: ngmanager-web
spec:
  type: NodePort
  ports:
    - port: 8888
      protocol: TCP
      targetPort: 8888
      nodePort: 31081
  selector:
    app: ngmanager-web