apiVersion: v1
kind: Service
metadata:
  namespace: ngmanager
  name: ngmanager-system
  labels:
    app: ngmanager-system
spec:
  ports:
    - port: 9010
      protocol: TCP
      name: grpc-port
    - port: 59011
      protocol: TCP
      name: broker-port
  selector:
    app: ngmanager-system